KFonline_v2/apps/cms/__init__.py
from .views import bp
from .models import CMSUser
import apps.cms.hooks

KFonline_v2/apps/cms/views.py
from flask import (
    Blueprint,
    render_template,
    views, request,
    session, redirect,
    url_for, g,
    jsonify)

from .forms import (
    LoginForm,
    ResetpwdForm,
    ResetEmailForm,
    AddBannerForm,
    UpdateBannerForm,
    AddBoardForm,
    UpdateBoardForm,
    UpdateUserForm,
    AddUserForm,
    AddFuserForm,
    UpdateFuserForm,
    AddrolesForm,
    UpdateRoleForm,
)


from .models import CMSUser, CMSPermission, cms_role_user, CMSRole
from ..front.models import FrontUser
from ..models import BannerModel, BoardModel, PostModel, HighlightPostModel, CommentModel
from .decorators import login_required, permission_required
import config
from exts import db, mail
from flask_mail import Message
from utils import restful, kfcache
import string
import random
from tasks import send_mail
from flask_paginate import Pagination,get_page_parameter

bp = Blueprint('cms', __name__, url_prefix='/cms')


@bp.route('/')
@login_required
def index():
    # g.cms_user
    return render_template('cms/cms_index.html')


@bp.route('/logout')
@login_required
def logout():
    # session.clear()
    del session[config.CMS_USER_ID]
    return redirect(url_for('cms.login'))


@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


@bp.route('/email_captcha/')
def email_captcha():
    email = request.args.get('email')
    if not email:
        return restful.params_error('请输入邮箱参数！')

    soure = list(string.ascii_letters)
    soure.extend(map(lambda x: str(x), range(0, 10)))
    captcha = ''.join(random.sample(soure, 6))

    # 给这个邮箱发送邮件
    # message = Message(
    #     '在线知识库邮箱验证',
    #     recipients=[email],
    #     body='您的验证码是：%s' % captcha
    # )
    # try:
    #     mail.send(message)
    # except:
    #     return restful.server_error()
    send_mail.delay('在线知识库邮箱验证',[email],'您的验证码是：%s' % captcha)
    kfcache.set(email, captcha)
    return restful.success()


@bp.route('/email/')
def send_email():
    message = Message(
        '在线系统邮件发送',
        recipients=['412880433@qq.com'],
        body='测试',
    )
    mail.send(message)
    return 'success'


@bp.route('/posts/')
@login_required
@permission_required(CMSPermission.POSTER)
def posts():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    posts = PostModel.query.slice(start,end)
    pagination = Pagination(bs_version=3,page=page,total=PostModel.query.count(),outer_window=0,inner_window=2)
    context = {
        'posts':posts,
        'pagination':pagination
    }


    return render_template('cms/cms_posts.html',**context)


@bp.route('/hpost/',methods=['GET','POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def hpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error(message='请传入帖子id')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子')

    highlight = HighlightPostModel()
    highlight.post = post
    db.session.add(highlight)
    db.session.commit()
    return restful.success()


@bp.route('/uhpost/',methods=['GET','POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def uhpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error(message='请传入帖子id')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子')

    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return restful.success()

@bp.route('/dpost/',methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def dpost():
    post_id = request.form.get('post_id')

    if not post_id:
        return restful.params_error(message='请传入帖子id')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error(message='没有这个板块')

    comments = CommentModel.query.filter_by(post_id=post_id).all()
    for comment in comments:
        db.session.delete(comment)
        db.session.commit()
    db.session.delete(post)
    db.session.commit()
    return restful.success()

@bp.route('/comments/')
@login_required
@permission_required(CMSPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


@bp.route('/boards/')
@login_required
@permission_required(CMSPermission.BOARDER)
def boards():
    board_models = BoardModel.query.all()
    context = {
        'boards': board_models
    }
    return render_template('cms/cms_boards.html', **context)


@bp.route('/aboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/uboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)

    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def dboard():
    board_id = request.form.get('board_id')

    if not board_id:
        return restful.params_error(message='请传入板块id！')

    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error(message='没有这个板块！')

    db.session.delete(board)
    db.session.commit()
    return restful.success()


@bp.route('/fusers/')
@login_required
@permission_required(CMSPermission.FRONTUSER)
def fusers():
    fusers_models = FrontUser.query.all()
    context = {
        'fusers':fusers_models
    }
    return render_template('cms/cms_fusers.html',**context)


@bp.route('/afuser/', methods=['POST'])
@login_required
@permission_required(CMSPermission.FRONTUSER)
def afuser():
    form = AddFuserForm(request.form)
    if form.validate():
        telephone = form.telephone.data
        username = form.username.data
        password = form.password.data
        user = FrontUser(telephone=telephone,username=username,password=password,)
        db.session.add(user)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dfuser/',methods=['POST'])
@login_required
@permission_required(CMSPermission.FRONTUSER)
def dfuser():
    user_id = request.form.get('user_id')
    print(user_id)
    if not user_id:
        return restful.params_error(message='请传入用户id')

    user = FrontUser.query.get(user_id)
    if not user_id:
        return restful.params_error(message='没有这个用户')
    db.session.delete(user)
    db.session.commit()
    return restful.success()


@bp.route('/ufuser/',methods=['POST'])
@login_required
@permission_required(CMSPermission.FRONTUSER)
def ufuser():
    form = UpdateFuserForm(request.form)
    if form.validate():
        user_id = form.user_id.data
        username = form.username.data
        telephone = form.telephone.data
        password = form.password.data
        user = FrontUser.query.get(user_id)
        if user:
            user.username = username
            user.telephone = telephone
            user.password = password
            db.session.commit()
            return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/cusers/')
@login_required
@permission_required(CMSPermission.CMSUSER)
def cusers():
    cusers_models = CMSUser.query.all()
    context = {
        'cusers':cusers_models
    }
    return render_template('cms/cms_cusers.html',**context)

@bp.route('/auser/', methods=['POST'])
@login_required
@permission_required(CMSPermission.CMSUSER)
def auser():
    form = AddUserForm(request.form)
    if form.validate():
        username = form.username.data
        password = form.password.data
        email = form.email.data
        user = CMSUser(username=username,password=password,email=email)
        db.session.add(user)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/uuser/',methods=['POST'])
@login_required
@permission_required(CMSPermission.CMSUSER)
def uuser():
    form = UpdateUserForm(request.form)
    if form.validate():
        user_id = form.user_id.data
        username = form.username.data
        email = form.email.data
        user = CMSUser.query.get(user_id)
        if user:
            user.username = username
            user.email = email
            db.session.commit()
            return restful.success()
    else:
        return restful.params_error(message=form.get_error())

@bp.route('/duser/',methods=['POST'])
@login_required
@permission_required(CMSPermission.CMSUSER)
def duser():
    user_id = request.form.get('user_id')

    if not user_id:
        return restful.params_error(message='请传入用户id')

    user = CMSUser.query.get(user_id)
    if not user_id:
        return restful.params_error(message='没有这个用户')
    db.session.delete(user)
    db.session.commit()
    return restful.success()

@bp.route('/croles/')
@login_required
@permission_required(CMSPermission.ALL_PERMISSION)
def croles():
    cmsusers = CMSUser.query.all()
    context = {
        'cmsusers':cmsusers
    }
    return render_template('cms/cms_croles.html',**context)

# @bp.route('/aroles/')
# @login_required
# @permission_required(CMSPermission.CMSUSER)
# def aroles():

KFonline_v2/apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    request,
    session,
    url_for,
    g,
    abort, redirect)

from .forms import SignupForm,SigninForm,AddPostForm,AddcommentForm
from utils import restful,safeutils
from .models import FrontUser
from exts import db
# from utils import safeutils
import config
from ..models import BannerModel, BoardModel, PostModel, CommentModel, HighlightPostModel
from .decorators import login_required
from flask_paginate import Pagination,get_page_parameter
from sqlalchemy.sql import func


bp = Blueprint('front',__name__)

@bp.route('/')
def index():
    board_id = request.args.get('bd',type=int,default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()
    sort = request.args.get('st',type=int,default=1)

    start = (page-1)*config.PER_PAGE
    end = start + config.PER_PAGE

    pasts = None
    total = 0

    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        #按照加精的时间倒序排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(),PostModel.create_time.desc())
    elif sort == 3:
        #按照点赞的数量排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())

    elif sort == 4:
        #按照评论的数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(
            PostModel.id).order_by(func.count(CommentModel.id).desc(),PostModel.create_time.desc())


    if board_id:
        query_obj = query_obj.filter(PostModel.board_id==board_id)
        posts = query_obj.slice(start,end)
        total = query_obj.count()
    else:
        posts = query_obj.slice(start,end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3,page=page,total=total,outer_window=0,inner_window=2)
    context = {
        'banners':banners,
        'boards':boards,
        'posts':posts,
        'pagination':pagination,
        'current_board':board_id,
        'current_sort':sort
    }
    return render_template('front/front_index.html',**context)

@bp.route('/logout/')
@login_required
def logout():
    # session.clear()
    del session[config.FRONT_USER_ID]
    return redirect(url_for('front.signin'))

@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html',post=post)


@bp.route('/acomment/',methods=['POST'])
@login_required
def add_comment():
    form = AddcommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这篇帖子')
    else:
        return restful.params_error(form.get_error())


@bp.route('/apost/',methods=['GET','POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html',boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title,content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())



class SignupView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template("front/front_signup.html", return_to=return_to)
        else:
            return render_template("front/front_signup.html")

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            # 需要验证手机号码唯一
            telephone = form.telephone.data
            username = form.username.data
            password = form.password.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            message = form.get_error()
            return restful.params_error(message=message)

class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and \
           return_to != request.url and \
           return_to != url_for("front.signin") and \
           safeutils.is_safe_url(return_to):
            return render_template("front/front_signin.html", return_to=return_to)
        else:
            return render_template("front/front_signin.html")

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remeber.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message='手机号或者密码错误！')
        else:
            return restful.params_error(message=form.get_error())

bp.add_url_rule("/signup/",view_func=SignupView.as_view("signup"))
bp.add_url_rule("/signin/",view_func=SigninView.as_view("signin"))

KFonline_v2/templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <script src="//cdn.staticfile.org/plupload/2.1.9/plupload.full.min.js"></script>
    <script src="//cdn.bootcss.com/plupload/2.1.9/i18n/zh_CN.js"></script>
    <script src="//cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.min.js"></script>

    <script src="{{ static('common/zlqiniu.js') }}"></script>
    <script src="{{ static('cms/js/banners.js') }}"></script>
    <style>
        .top-box button {
            float: right;
        }
    </style>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>名称</th>
            <th>图片链接</th>
            <th>跳转链接</th>
            <th>优先级</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
            {% for banner in banners %}
                <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}" data-id="{{ banner.id }}">
                    <td>{{ banner.name }}</td>
                    <td>{{ banner.image_url }}</td>
                    <td>{{ banner.link_url }}</td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-banner-btn" >编辑</button>
                        <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>

    <!-- Modal -->
    <div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">轮播图</h4>
                </div>
                <div class="modal-body">
                    <form action="" class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">名称：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">图片：</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                            </div>
                            <button class="btn btn-info col-sm-2" id="upload-btn">添加图片</button>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">跳转：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权重：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="priority" placeholder="优先级">
                            </div>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

KFonline_v2/templates/cms/cms_base.html
{% from 'common/_macros.html' import static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    {% include 'common/_heads.html' %}
    <link rel="stylesheet" href="{{ static('cms/css/base.css') }}">
    <script src="{{ static('cms/js/base.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">在线知识库cms管理后台</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{url_for('cms.profile')}}">{{ g.cms_user.username }}</a></li>
                <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>
                {% set cms_user = g.cms_user %}
                <li class="nav-group banner-manage"><a href="{{url_for('cms.banners')}}">轮播图管理</a></li>
                {% if cms_user.has_permission(CMSPermission.POSTER) %}
                <li class="nav-group post-manage"><a href="{{url_for('cms.posts')}}">帖子管理</a></li>
                {% endif %}
<!--                {% if cms_user.has_permission(CMSPermission.COMMENTER) %}-->
<!--                <li class="comments- manage"><a href="{{url_for('cms.comments')}}">评论管理</a></li>-->
<!--                {% endif %}-->
                {% if cms_user.has_permission(CMSPermission.BOARDER) %}
                <li class="board-manage"><a href="{{url_for('cms.boards')}}">模块管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.BOARDER) %}
                <li class="nav-group user-manage"><a href="{{url_for('cms.fusers')}}">前台用户管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.CMSUSER) %}
                <li class="nav-group cmsuser-manage"><a href="{{url_for('cms.cusers')}}">CMS用户管理</a></li>
                {% endif %}
                {% if cms_user.is_developer %}
                <li class="cmsrole-manage"><a href="{{url_for('cms.croles')}}">cms组管理</a></li>
                {% endif %}

            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

KFonline_v2/templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    板块管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" style="float: right" id="add-board-btn">添加新版块</button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>版块名称</th>
            <th>帖子数量</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                <td>{{ board.name }}</td>
                <td>0</td>
                <td>{{ board.create_time }}</td>
                <td>
                    <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                    <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

KFonline_v2/templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    评论管理
{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
我是评论管理
{% endblock %}

KFonline_v2/templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
角色管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/roles.js') }}"></script>
{% endblock %}

{% block page_title %}
{{ self.title() }}
{% endblock %}

{% block main_content %}
<div class="top-box hidden">
    <button class="btn btn-warning" style="float: right"  data-toggle="modal" data-target="#roles-dialog">添加新用户</button>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>用户名称</th>
        <th>角色</th>
        <th>权限</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>

    {% for cmsuser in cmsusers %}
    <tr data-name="{{ cmsuser.username }}" data-id="{{ cmsuser.id }}" >
        {% set user = cmsuser %}
        <td>{{ cmsuser.username }}</td>
        <td>{% for role in user.roles %}
                        {{ role.name }}
                        {% if not loop.last %},{% endif %}
                    {% endfor %}
        </td>
        <td>{% for role in user.roles %}
                        {{ role.desc }}
                        {% if not loop.last %}/{% endif %}
                    {% endfor %}
        </td>
        <td>
{#            <button class="btn btn-default btn-xs change-user-btn">修改权限</button>#}
            <button class="btn btn-danger btn-xs delete-user-btn">删除</button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
 <div class="modal fade" id="roles-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加用户权限</h4>
                </div>
                <div class="modal-body">
                    <form action="" class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">email：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="email" placeholder="email">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">角色：</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="role" placeholder="角色">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="save-role-btn">保存</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

KFonline_v2/templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    在线知识库cms管理系统
{% endblock %}

{% block page_title %}
    欢迎来到在线知识库cms管理系统
{% endblock %}

KFonline_v2/templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    帖子管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/posts.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>标题</th>
            <th>发布时间</th>
            <th>模块</th>
            <th>作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }}">
                <td><a target="_blank" href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a></td>
                <td>{{ post.create_time }}</td>
                <td>{{ post.board.name }}</td>
                <td>{{ post.author.username }}</td>
                <td>
                    {% if post.highlight %}
                        <button class="btn btn-default btn-xs highlight-btn">取消提醒</button>
                    {% else %}
                        <button class="btn btn-default btn-xs highlight-btn" >重点更新</button>
                    {% endif %}
                    <button class="btn btn-danger btn-xs delete-post-btn">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div style="text-align: center">
        {{ pagination.links }}
    </div>
{% endblock %}